services:
  node-dev:
    build:
      context: .
      target: jerbooru-node-dev
    image: jerbooru-node-dev
    volumes:
      - ./src:/app/src
    environment:
      - HI=HI
    ports:
      - "3000:3000"

  node-prod:
    build:
      context: .
      target: jerbooru-node-prod
    image: jerbooru-node-prod
    environment:
      - HI=HI
    ports:
      - "3000:80"
  
  postgres-dev:
    build:
      context: .
      target: jerbooru-postgres-dev
    image: jerbooru-postgres-dev
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=HI
      - POSTGRES_USER=HI
      - POSTGRES_DB=HI
    ports:
      - "5432:2345"

  postgres-prod:
    build:
      context: .
      target: jerbooru-postgres-prod
    image: jerbooru-postgres-prod
    volumes:
      - /var/lib/postgres
    environment:
      - POSTGRES_PASSWORD=HI
      - POSTGRES_USER=HI
      - POSTGRES_DB=HI
    ports:
      - "5432:5432"